# Generated by Django 4.2.7 on 2024-04-21 03:06

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Create_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update_at',
            new_name='update_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='create_at',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update_at',
            new_name='update_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='keywords',
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
